### ISSUE TITLE
[Feature Request] Mythic weapon focus/specializarion

### ISSUE THREAD

**Issue by jsalazarloyola** [dmrickey/fvtt-ckl-roll-bonuses#16]
Hi,

I'd like to ask for a new feature to include mythic weapon focus or specialization in the bonuses. To be honest, I would try to do it myself, but I don't have the time at the moment (and my Javascript is very rusty right now) 🥲 

Thanks :D

**Comment by dmrickey** [comment]
I should have done this a while ago but I overlooked that this feat was available. I'll try to include it in my next update

**Comment by dmrickey** [comment]
@jsalazarloyola 
Implemented in 2.7.6
