### ISSUE TITLE
[BUG]  DC bonus not working correctly.

### ISSUE THREAD

**Issue by vasseaude** [dmrickey/fvtt-ckl-roll-bonuses#24]
### Applying DC Bonues to anything other than spell does not appear to work.

> I am trying to apply the Ability Focus Feat. It does not appear to work on anything but spells.
> I suspect the cause to be in line 95 of the dc-bonus.mjs file.

```

93        if (!actor
94            || !value
95            || !(item instanceof pf1.documents.item.ItemSpellPF)
96           || !rollData
97        ) {
98            return;
99        }

```
It will only apply the DC Bonus if it is a spell. The line should be changed to
`|| !(item instanceof pf1.documents.item.ItemPF)`
or eliminated entirely as it seems unnecessary based on the code that proceeds it.
The recent update broke it again, reminding me to post this.
I can be reached on discord if any additional information is necessary, as we seem to share a good number of servers.
Username: kentonstone

**Comment by dmrickey** [comment]
Fixed in https://github.com/dmrickey/fvtt-ckl-roll-bonuses/releases/tag/2.11.2
