### ISSUE TITLE
[BUG] Bonuses doesn't apply to Versatile Performance

### ISSUE THREAD

**Issue by Kubixcube** [dmrickey/fvtt-ckl-roll-bonuses#28]
**Describe the bug**
When there is a bonus to skills check linked to a Versatile Performance, the bonuses don't apply.
Example : Progidy (Perform - Oratory) --> Checks to Perform (oratory)/Diplomacy/Sense Motive doesn't have the bonus.

**To Reproduce**
1. Set a versatile performance
2. Use an item that gives a bonus to thoses checks (exemple a feat)
3. Roll the check

**Expected behavior**
Normally, all the bonuses that the Perform skill has is applied 
to all linked Versatile Performance skills checks

**Screenshots**
![RB](https://github.com/dmrickey/fvtt-ckl-roll-bonuses/assets/62657097/cb1ac2d1-6d01-4ba0-ae4b-357b6646444a)

**What version of Roll Bonuses and PF1 are you using?**
Roll Bonuses: 2.12.2
pf1: 10.2
foundry : 11.315

**Additional context**
Also there are several Perform skills that shows when I try to select the buff target, I don't think it is expected.
(Sorry my game is in french)

**Comment by dmrickey** [comment]
This appears to be an issue with the system itself. Changes aren't being included in skill rolls. (make a super obvious change like +1000 to a specific skill, the skill bonus will show up in the skills list, but when you roll it's not included).

![image](https://github.com/dmrickey/fvtt-ckl-roll-bonuses/assets/3664822/6ebe750f-a325-49b5-9d06-51445233db8e)

**Comment by dmrickey** [comment]
Fixed in 2.12.3
