### ISSUE TITLE
A reach weapon against height does not calculate 

### ISSUE THREAD

**Issue by Yonman17** [dmrickey/fvtt-ckl-roll-bonuses#39]
**Describe the bug**
Attacker has a reach weapon and it is trying to attack a creature 10' directly above it you get a message saying it's not close enough.

![image](https://github.com/user-attachments/assets/57b34325-4719-4a5b-bc17-63644929d3c2)

**Comment by dmrickey** [comment]
This has been fixed for the next release (current release is 2.14.4 so anything after that). I'll leave this open until I release the next version (or at least until after I remember to come back and close it 😅)

**Comment by dmrickey** [comment]
Fixed in 2.15.0
