### ISSUE TITLE
[Feature] Add a Critical Confirm bonus

### ISSUE THREAD

**Issue by Baldrax** [dmrickey/fvtt-ckl-roll-bonuses#48]
I was attempting to set up the **Samurai** class feature **Weapon Expertise** which grants a bonus to confirm critical attacks to the chosen weapon type and I noticed there appears to be no option for this. Unless I missed a way to achieve this.

For now I am adding that manually in the attack entry for the character.

**Comment by dmrickey** [comment]
This should be doable. I'll add it to my list
