### ISSUE TITLE
Roll Bonuses is interfering with PF1s skipDialog Roll Option

### ISSUE THREAD

**Issue by lyka473** [dmrickey/fvtt-ckl-roll-bonuses#9]
With the Roll Bonuses module active, the skipDialog option is not functioning within scripts and script calls. It still works when holding down the shift key.

Reproduction steps:

- Create an item with a script call such as `actor.rollSkill("int", { skipDialog: true });`
- Use the action - the roll dialog will appear if module is enabled.

No errors present in console

Foundry v10.291
Pathfinder 1 9.4
Roll Bonuses 2.4.0

**Comment by dmrickey** [comment]
I have this resolved for the next version.

**Comment by dmrickey** [comment]
I have this resolved for the next version (2.5.0 in case I forget to come back and close this issue).

**Comment by dmrickey** [comment]
If you know what you're doing (or really even if you don't) you can open up the mode files locally and make this change to fix it immediately instead of waiting for the update I'm currently working on
https://github.com/dmrickey/fvtt-ckl-roll-bonuses/commit/49c8944103b928cf88952fc9b667d96bc881325b

**Comment by lyka473** [comment]
The fix worked great, thank you!

**Comment by dmrickey** [comment]
Next version that includes this fix is officially out now
